#!/usr/bin/env bash
# Script Description: Install and configure HAproxy on a new Ubuntu machine.
# Install HAproxy
# Configure HAproxy
# Enable HAproxy init script
# Restart HAproxy to apply changes

sudo apt-get -y update
sudo apt-get install -y haproxy

server_config=\
"
frontend  mohamedmo3iz
        bind *:80
        mode http
        default_backend mohamedmo3iz
backend mohamedmo3iz
        balance roundrobin
        server 469212-web-01 18.233.62.225:80 check
        server 469212-web-02 52.91.116.153:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart








